### ISSUE TITLE
При переходе между страницами слетает язык

### ISSUE THREAD

**Issue by kpozdnikin** [kpozdnikin/wordpressProject#2]
Главная - Услуги

**Comment by tihero87** [comment]
Исправил
        <?php 
            if(pll_current_language() == 'ru'){
                $prefix_href = "";
                $blog = "блог/";
                $services = "услуги/";

            }elseif (pll_current_language() == "en") {
                $prefix_href = "en/";
                $blog = "blog/";
                $services = "services/";
            }elseif (pll_current_language() == "es") {
                $prefix_href = "es/";
                $blog = "el-blog/";
                $services = "servicios/";               
            }
        ?>           
            <ul class="nav" onclick="bodyFree()">
                <li><a href="<?php echo '/' .$prefix_href ?>"><?php echo $smm_menu_main; ?></a></li>
                <li><a href="<?php echo '/' .$prefix_href. '#presentation' ?>"><?php echo $smm_menu_about; ?></a></li>
                <li><a href="<?php echo '/' .$prefix_href .$services ?>"><?php echo $smm_menu_services; ?></a></li>
                <li><a href="<?php echo '/' .$prefix_href .$blog ?>"><?php echo $smm_menu_blog; ?></a></li>
                <li><a href="<?php echo '#contacts' ?>"><?php echo $smm_menu_contacts; ?></a></li>
            </ul>
